"""
Check the HTML size generated by folium for different marker counts
"""
import folium
import pandas as pd

def test_map_size(num_markers):
    # Generate test data
    test_df = pd.DataFrame({
        'Latitude': [25 + (i % 60) * 0.1 for i in range(num_markers)],
        'Longitude': [-97 + (i % 150) * 0.1 for i in range(num_markers)],
        'ColonyName': [f'Colony {i}' for i in range(num_markers)],
        'BirdCount': [100 + i for i in range(num_markers)]
    })

    # Create map
    m = folium.Map(
        location=[27.5, -90.0],
        zoom_start=6,
        tiles='OpenStreetMap',
        control_scale=True
    )

    # Add markers with full tooltips like the real app
    for idx, row in test_df.iterrows():
        tooltip_text = f"<b>ColonyName:</b> {row['ColonyName']}<br><b>BirdCount:</b> {row['BirdCount']}"
        folium.Marker(
            location=[row['Latitude'], row['Longitude']],
            tooltip=folium.Tooltip(tooltip_text, sticky=True),
            popup=folium.Popup(tooltip_text, max_width=300),
            icon=folium.Icon(color='blue', icon='info-sign', prefix='glyphicon')
        ).add_to(m)

    # Get HTML
    html = m._repr_html_()
    size_bytes = len(html.encode('utf-8'))
    size_mb = size_bytes / (1024 * 1024)

    print(f"{num_markers:4d} markers: {size_mb:6.2f} MB ({size_bytes:,} bytes)")
    return size_bytes

print("Testing HTML size for different marker counts:")
print("-" * 60)

for size in [50, 100, 190, 200, 300, 400, 445, 500]:
    test_map_size(size)
